# Generated by Django 4.1.1 on 2022-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('grocery_item', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
