# Generated by Django 4.1.1 on 2022-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField(max_length=2048)),
                ('short_url', models.CharField(max_length=6)),
            ],
        ),
    ]
