# Generated by Django 4.1.1 on 2022-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=200)),
                ('long_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
