# Generated by Django 4.1.1 on 2022-09-30 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo_list",
            name="finish_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
