# Generated by Django 4.1.1 on 2022-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0002_todo_list_finish_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(max_length=1000)),
            ],
        ),
    ]
