# Generated by Django 4.1.1 on 2022-09-24 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myitem', models.CharField(max_length=200)),
                ('myauthor', models.CharField(max_length=200, null=True)),
                ('mydescription', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 9, 24, 3, 27, 18, 770101, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
    ]
