# Generated by Django 4.1.1 on 2022-09-27 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mymodel_active_alter_mymodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='active',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 1, 38, 15, 191316, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
