# Generated by Django 4.1.1 on 2022-09-29 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_groceryitem_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 3, 45, 37, 833998, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 3, 45, 37, 833998, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
