let footerDisplay = document.querySelector('#footerDisplay')
let displayHacks = document.querySelector('#displayHacks')



var phrases = [
    "&nbsp;",
    "&ensp;",
    "&emsp;",
    "&nbsp;",
    "&ensp;",
    "&emsp;",
    "&ensp;",
    "&emsp;",
    "&ensp;",
    "&emsp;",
    "&ensp;",
    "&emsp;",
    "</br>&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;",
    "</br>",
    "if (condition) {",
    "else {",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "   ",
    "    ",
    "  ",
    " ",
    "while (condition) {",
    "for (var i = 0; i < array.length; i++) {",
    "break;",
    "continue;",
    "switch (expression) {",
    "case label:",
    "function myFunction(x, y, z) {",
    "return x * y * z;",
    "console.log();",
    "console.warn();",
    "console.error();",
    "alert();",
    "prompt();",
    "confirm();",
    "document.getElementById();",
    "document.getElementsByClassName();",
    "document.getElementsByTagName();",
    "this;",
    "window;",
    "Math.random();",
    "Math.round();",
    "Math.floor();",
    "Math.ceil();",
    "Math.abs();",
    "isNaN();",
    "parseFloat();",
    "parseInt();",
    "Number();",
    "Infinity;",
    "NaN;",
    "Array.isArray();",
    "Array.prototype.forEach();",
    "Array.prototype.map();",
    "Array.prototype.filter();",
    "Date();",
    "new Date();",
    "Date.now();",
    "Date.prototype.getFullYear();",
    "Date.prototype.getMonth();",
    "Date.prototype.getDate();",
    "Date.prototype.getHours();",
    "Date.prototype.getMinutes();",
    "Date.prototype.getSeconds();",
    "Date.prototype.getMilliseconds();",
    "Date.prototype.getTime();",
    "Date.prototype.toDateString();",
    "String();",
    "new String();",
    "String.prototype.length;",
    "String.prototype.toUpperCase();",
    "String.prototype.toLowerCase();",
    "String.prototype.substr();",
    "String.prototype.substring();",
    "String.prototype.split();",
    "String.prototype.trim();",
    "RegExp();",
    "new RegExp();",
    "RegExp.prototype.test();",
    "exec();",
    "Object();",
    "new Object();",
    "JSON.stringify();",
    "JSON.parse();",
    "new XMLHttpRequest();",
    "encodeURI();",
    "decodeURI();",
    "encodeURIComponent();",
    "decodeURIComponent();",
    "escape();",
    "unescape();",
    "isFinite();",
    "isInteger();",
    "isSafeInteger();",
    "isNaN();",
    "isPrototypeOf();",
    "hasOwnProperty();",
    "propertyIsEnumerable();",
    "toString();",
    "valueOf();",
    "toLocaleString();",
    "toFixed();",
    "toExponential();",
    "toPrecision();",
    "assert();",
    "dir();",
    "dirxml();",
    "group();",
    "groupEnd();",
    "time();",
    "timeEnd();",
    "profile();",
    "profileEnd();",
    "count();",
    "exception();",
    "table();",
    "trace();",
    "clear();"
    ]


document.addEventListener('keypress', (event) => {

    let randomPhrase = Math.floor(Math.random() * (phrases.length - 0) + 0)
    let shownPhrase = phrases[randomPhrase]
    window.scrollTo(0, document.body.scrollHeight);
    displayHacks.innerHTML = displayHacks.innerHTML + shownPhrase
    console.log(shownPhrase)
})


