# Generated by Django 4.1.1 on 2022-09-27 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 22, 10, 52, 480826, tzinfo=datetime.timezone.utc), null=True)),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
