# Generated by Django 4.1.1 on 2022-09-27 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='complete',
            field=models.BooleanField(blank=True, default=0, verbose_name='Complete?'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 23, 23, 42, 860084, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
