# Generated by Django 4.1.1 on 2022-09-27 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_alter_groceryitem_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 23, 24, 57, 638308, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
