# Generated by Django 4.1.1 on 2022-09-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0003_alter_groceryitem_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
