# Generated by Django 4.1.1 on 2022-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_mytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='mytext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
