# Generated by Django 4.1.1 on 2022-10-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='shrink',
        ),
    ]
