# Generated by Django 4.1.1 on 2022-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0002_rename_mymodel_shrink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shrink',
            old_name='name',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='shrink',
            name='long_url',
        ),
        migrations.AlterField(
            model_name='shrink',
            name='short_url',
            field=models.URLField(max_length=5),
        ),
    ]
