# Generated by Django 4.1.1 on 2022-10-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shrinker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convexurl',
            old_name='long_url',
            new_name='longURL',
        ),
    ]
