# Generated by Django 4.1.1 on 2022-10-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shrinker', '0002_rename_long_url_convexurl_longurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='convexurl',
            name='http_referral',
            field=models.TextField(max_length=220, null=True),
        ),
    ]
