# Generated by Django 4.1.2 on 2022-10-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
    ]
