# Generated by Django 4.1.1 on 2022-09-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerys',
            name='quanity',
            field=models.IntegerField(default=1),
        ),
    ]
