# Generated by Django 4.1.1 on 2022-09-30 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_genre', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=255)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('completeBy_date', models.DateField(default=datetime.date.today)),
                ('task_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
