# Generated by Django 4.1.1 on 2022-09-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date_complete',
            field=models.DateField(null=True),
        ),
    ]
