# Generated by Django 4.1.1 on 2022-09-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
