# Generated by Django 4.1.1 on 2022-09-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0002_groceryitem_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
