# Generated by Django 4.1.1 on 2022-11-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_userpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
