# Generated by Django 4.1.1 on 2022-10-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('meta', models.TextField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url_long', models.URLField()),
                ('url_short', models.CharField(max_length=200, null=True)),
                ('url_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UrlLinks', to='url_shortener_app.urlmeta')),
            ],
        ),
    ]
