# Generated by Django 4.1.1 on 2022-10-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllink',
            name='url_short',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
