# Generated by Django 4.1.1 on 2022-10-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metauser',
            old_name='testfield',
            new_name='UrlLink',
        ),
    ]
