# Generated by Django 4.1.1 on 2022-10-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urllink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='urllink',
            name='url_short',
        ),
    ]
