# Generated by Django 4.1.1 on 2022-10-05 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metauser',
            name='UrlLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urlLinks', to='url_shortener_app.urllink'),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='meta',
            field=models.CharField(max_length=10000),
        ),
    ]
