# Generated by Django 4.1.1 on 2022-09-23 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfield', models.CharField(max_length=200)),
                ('myauthor', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 9, 23, 4, 32, 0, 193054, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
    ]
