# Generated by Django 4.1.1 on 2022-09-23 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 4, 35, 20, 47308, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
