# Generated by Django 4.1.2 on 2022-10-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortner_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="urlshortner",
            old_name="url",
            new_name="long_url",
        ),
        migrations.AddField(
            model_name="urlshortner",
            name="short_code",
            field=models.CharField(default="https://www.google.com", max_length=200),
            preserve_default=False,
        ),
    ]
