# Generated by Django 4.1.1 on 2022-09-23 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
