# Generated by Django 4.1.1 on 2022-09-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=208)),
                ('director', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('in_theatres', models.BooleanField()),
            ],
        ),
    ]
