# Generated by Django 4.1.2 on 2022-10-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gravy_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-date_created"]},
        ),
    ]
