# Generated by Django 4.1.2 on 2022-10-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gravy_app", "0002_alter_blogpost_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
