# Generated by Django 4.1.1 on 2022-09-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
